#!/bin/sh

REF=ecoli.ref.fa
VCF=ecoli.pan3.vcf.gz
PREFIX=ecoli.pan3

# build the graph
vg construct --reference $REF --vcf $VCF --alt-paths --flat-alts --node-max 1000 > $PREFIX.vg

# build the GBWT index
# NOTE: use --force-phasing to get single thread paths from a "forced" phase
vg index --threads 64 --compact --xg-name $PREFIX.xg --gbwt-name $PREFIX.gbwt --force-phasing --vcf-phasing $VCF -g $PREFIX.gcsa $PREFIX.vg

# extract the threads from the GBWT as vg Paths
vg paths -x $PREFIX.xg -g $PREFIX.gbwt -V -q _thread_ecoli1 > ecoli1_paths.vg
vg paths -x $PREFIX.xg -g $PREFIX.gbwt -V -q _thread_ecoli2 > ecoli2_paths.vg
vg paths -x $PREFIX.xg -g $PREFIX.gbwt -V -q _thread_ecoli3 > ecoli3_paths.vg

# now add those paths back to the vg
cat $PREFIX.vg *_paths.vg > $PREFIX.paths.vg
rm *_paths.vg

# output some nice files
vg view --threads 64 --gfa $PREFIX.paths.vg > $PREFIX.paths.gfa
vg view --threads 64 --json $PREFIX.paths.vg > $PREFIX.paths.json
vg view --threads 64 --dot $PREFIX.paths.vg > $PREFIX.paths.dot
dot -Tpdf $PREFIX.paths.dot > $PREFIX.paths.pdf
