#!/bin/sh

java -cp classes:lib/commons-cli-2.0.jar:lib/axis.jar:lib/jaxrpc.jar:lib/commons-logging-1.0.4.jar:lib/commons-discovery-0.2.jar:lib/wsdl4j-1.5.1.jar:lib/activation-1_0_2.jar:lib/mailapi-1_3_1.jar:lib/cog-jglobus.jar org.ncgr.opal.MemeClient http://localhost:8080/opal2/services/meme $1 $2 $3 $4 $5 $6 $7 $8 $9
