#!/bin/sh
java -cp build/libs/ncgr-jphyloio.jar:libs/bioinfweb-commons-java-bio-3.0.0.jar:libs/bioinfweb-commons-java-core-3.2.0.jar:libs/commons-collections4-4.1.jar:libs/owlapi-XMLUtils-4.1.4.jar \
       	info.bioinfweb.jphyloio.demo.tree.Application
