#!/bin/sh
NEWICKFILE=/data/v2/LEGUMES/Fabaceae/genefamilies/legume.genefam.fam1.M65K/legume.genefam.fam1.M65K.trees_ML_rooted/legfed_v1_0.L_VNJ086

java -classpath "build/install/ncgr-jphyloio/lib/*" ReadTree $NEWICKFILE
