#!/bin/sh
# usage: VCFSegregation
#  -caseval <arg>                case value in dbGaP phenotype file (e.g.
#                                Case)
#  -ccv,--casecontrolvar <arg>   case/control variable in dbGaP phenotype
#                                file (e.g. ANALYSIS_CAT)
#  -controlval <arg>             control value in dbGaP phenotype file (e.g.
#                                Control)
#  -dn,--diseasename <arg>       desired case disease name in dbGaP
#                                phenotype file (e.g. Schizophrenia;
#                                required if -dv)
#  -ds,--desiredsex <arg>        phenotype value of desired sex (e.g. M or
#                                1)
#  -dv,--diseasevar <arg>        disease variable in dbGaP phenotype file
#                                (e.g. PRIMARY_DISEASE; required if -dn)
#  -mnc,--maxnocalls <arg>       maximum number of no-calls for a locus to
#                                be output (1000)
#  -mv,--minvars <arg>           minimum number of VAR calls for a locus to
#                                be output (0)
#  -pf,--phenofile <arg>         dbGaP phenotype file
#  -sf,--samplefile <arg>        dbGaP samples file (needed if contains
#                                mapping from dbGaP_Subject_ID to sample ID
#                                used in VCF file)
#  -sv,--samplevar <arg>         study sample ID variable in dbGaP samples
#                                file (e.g. SAMPID; required if -sf)
#  -vf,--vcffile <arg>           VCF file

## maps to GRCh38
## /erdos/ncbi/VCF/AREDS/Affy_gru_merge-GRCh38.norm.vcf.gz
## /erdos/ncbi/VCF/AREDS/Illumina_gru_merge-GRCh38.norm.vcf.gz

# ## NOTE: no disease name or disease var
# VCFFILE=/erdos/shokin/ncbi/VCF/AREDS/Affy_gru_merge-GRCh38.norm.vcf.gz
# PHENODIR=/erdos/shokin/ncbi/dbGaP-22329/PhenoGenotypeFiles/RootStudyConsentSet_phs000001.AREDS.v3.p1.c2.GRU/PhenotypeFiles
# PHENOFILE=$PHENODIR/phs000001.v3.pht000371.v2.p1.c2.amdlensphenotype.GRU.txt
# SAMPLEFILE=$PHENODIR/phs000001.v3.pht002478.v1.p1.AREDS_Sample.MULTI.txt
# SAMPLEVAR=specnum
# CASECONTROLVAR=AMDSTAT
# CASEVAL=11
# CONTROLVAL=1
# OUTFILE=AREDS

# java -server -Xms1g -Xmx600g -XX:+UseG1GC -XX:+UseStringDeduplication -cp "build/install/gwas/lib/*" org.ncgr.gwas.VCFSegregation $1 \
#      -vf $VCFFILE \
#      -pf $PHENOFILE \
#      -sf $SAMPLEFILE \
#      -sv $SAMPLEVAR \
#      -ccv $CASECONTROLVAR -caseval $CASEVAL -controlval $CONTROLVAL \
#      > $OUTFILE.seg.txt

# VCFFILE=/erdos/shokin/ncbi/VCF/GenomicPsychiatryCohort/c1_gpc.vcf.gz
# PHENODIR=/erdos/shokin/ncbi/dbGaP-20036/PhenoGenotypeFiles/RootStudyConsentSet_phs001020.GenomicPsychiatryCohort.v1.p1.c1.DS-SZRD/PhenotypeFiles
# PHENOFILE=phs001020.v1.pht005783.v1.p1.c1.GPC_WGS_Subject_Phenotypes.DS-SZRD.txt
# SAMPLEFILE=phs001020.v1.pht005782.v1.p1.GPC_WGS_Sample.MULTI.txt
# SAMPLEVAR=SAMPID
# DISEASENAME=Schizophrenia
# DISEASEVAR=PRIMARY_DISEASE
# CASECONTROLVAR=ANALYSIS_CAT
# CASEVAL=Case
# CONTROLVAL=Control
# MINVARS=10
# MAXNOCALLS=10
# DESIREDSEX=
# OUTFILE=GenomicPsychiatryCohort

VCFFILE=/erdos/shokin/ncbi/VCF/SchizophreniaSwedish_Sklar/swe.vcf.gz
PHENODIR=/erdos/shokin/ncbi/dbGaP-20036/PhenoGenotypeFiles/RootStudyConsentSet_phs000473.SchizophreniaSwedish_Sklar.v2.p2.c1.GRU/PhenotypeFiles
PHENOFILE=phs000473.v2.pht002600.v2.p2.c1.Schizophrenia_Swedish_Subject_Phenotypes.GRU.txt
SAMPLEFILE=phs000473.v2.pht002599.v2.p2.Schizophrenia_Swedish_Sample.MULTI.txt
SAMPLEVAR=SAMPID
DISEASENAME=Schizophrenia
DISEASEVAR=PRIMARY_DISEASE
CASECONTROLVAR=ANALYSIS_CAT
CASEVAL=Case
CONTROLVAL=Control
MINVARS=100
MAXNOCALLS=100
OUTFILE=SchizophreniaSwedish_Sklar

java -server -Xms1g -Xmx600g -XX:+UseG1GC -XX:+UseStringDeduplication -cp "build/install/gwas/lib/*" org.ncgr.gwas.VCFSegregation $1 \
     -vf $VCFFILE \
     -pf $PHENODIR/$PHENOFILE \
     -sf $PHENODIR/$SAMPLEFILE \
     -sv $SAMPLEVAR \
     -dn $DISEASENAME \
     -dv $DISEASEVAR \
     -mv $MINVARS \
     -mnc $MAXNOCALLS \
     -ccv $CASECONTROLVAR -caseval $CASEVAL -controlval $CONTROLVAL


##     > $OUTFILE.seg.txt
