#!/bin/sh
##usage: VCFSegSubjects
## -caseval <arg>                case value in dbGaP phenotype file (e.g.
##                               Case)
## -ccv,--casecontrolvar <arg>   case/control variable in dbGaP phenotype
##                               file (e.g. ANALYSIS_CAT)
## -controlval <arg>             control value in dbGaP phenotype file (e.g.
##                               Control)
## -d,--debug                    enable debug mode
## -dn,--diseasename <arg>       desired case disease name in dbGaP
##                               phenotype file (e.g. Schizophrenia;
##                               required if -dv)
## -dv,--diseasevar <arg>        disease variable in dbGaP phenotype file
##                               (e.g. PRIMARY_DISEASE; required if -dn)
## -pf,--phenofile <arg>         dbGaP phenotype file
## -sf,--samplefile <arg>        dbGaP samples file (needed if contains
##                               mapping from dbGaP_Subject_ID to sample ID
##                               used in VCF file)
## -sv,--samplevar <arg>         study sample ID variable in dbGaP samples
##                               file (e.g. SAMPID; required if -sf)

## maps to GRCh38
## /erdos/ncbi/VCF/AREDS/Affy_gru_merge-GRCh38.norm.vcf.gz
## /erdos/ncbi/VCF/AREDS/Illumina_gru_merge-GRCh38.norm.vcf.gz

PHENOFILE="/erdos/shokin/ncbi/dbGaP-22329/PhenoGenotypeFiles/RootStudyConsentSet_phs000001.AREDS.v3.p1.c2.GRU/PhenotypeFiles/phs000001.v3.pht000371.v2.p1.c2.amdlensphenotype.GRU.txt"
SAMPLEFILE="/erdos/shokin/ncbi/dbGaP-22329/PhenoGenotypeFiles/RootStudyConsentSet_phs000001.AREDS.v3.p1.c2.GRU/PhenotypeFiles/phs000001.v3.pht002478.v1.p1.AREDS_Sample.MULTI.txt"
CASEVAL=11
CONTROLVAL=1
CASECONTROLVAR="AMDSTAT"
SAMPLEVAR="specnum"
ZYGOSITY="HET"

java -server -cp "build/install/gwas/lib/*" org.ncgr.gwas.VCFSegSubjects  \
     -pf $PHENOFILE -sf $SAMPLEFILE -sv $SAMPLEVAR -ccv $CASECONTROLVAR -caseval $CASEVAL -controlval $CONTROLVAL > AREDS.labels.txt

