#!/bin/sh
vcftools --gzvcf /home/localhost/shokin/erdos/1000G/ALL.chr11.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz \
	 --recode --chr 11 --from-bp 5240000 --to-bp 5250000 --indv $1 --out $1
