#!/bin/sh
## rs3334 is at 11:5248232

## maximum supported value of node-max is 1024
NODEMAX=1024

REF=/erdos/shokin/hs37d5/hs37d5.11.fa

## just the HBB gene
VCF=HBB.vcf.gz
PREFIX=HBB
REGION=11:5246696-5248301

# ## a 10k region around HBB
# VCF=HBB.10k.vcf.gz
# PREFIX=HBB.10k
# REGION=11:5240000-5250000

# ## a 5k region around HBB
# VCF=HBB.5k.vcf.gz
# PREFIX=HBB.5k
# REGION=11:5246000-5251000

# ## a 3k region around HBB
# VCF=HBB.3k.vcf.gz
# PREFIX=HBB.3k
# REGION=11:5246000-5249000

# ## a 236b region at the end of HBB containing rs334
# VCF=HBB.236.vcf.gz
# PREFIX=HBB.236
# REGION=11:5248066-5248301

# ## a 128b region at the end of HBB containing rs334
# VCF=HBB.128.vcf.gz
# PREFIX=HBB.128
# REGION=11:5248174-5248301

# ## a 57b region around rs334
# VCF=HBB.57.vcf.gz
# PREFIX=HBB.57
# REGION=11:5248206-5248262

# ## a 20kb region centered on rs334
# VCF=HBB.20k.vcf.gz
# PREFIX=HBB.20k
# REGION=11:5238232-5258232

# build the graph
echo "vg construct --threads 64 --reference $REF --vcf $VCF --region $REGION --alt-paths --flat-alts --node-max $NODEMAX > $PREFIX.vg"
vg construct --threads 64 --reference $REF --vcf $VCF --region $REGION --alt-paths --flat-alts --node-max $NODEMAX > $PREFIX.vg

# build the GBWT index
# NOTE: use --force-phasing to get single thread paths from a "forced" phase
echo "vg index --threads 64 --compact --xg-name $PREFIX.xg --gbwt-name $PREFIX.gbwt --force-phasing --vcf-phasing $VCF -g $PREFIX.gcsa $PREFIX.vg"
vg index --threads 64 --compact --xg-name $PREFIX.xg --gbwt-name $PREFIX.gbwt --vcf-phasing $VCF -g $PREFIX.gcsa $PREFIX.vg

# extract the threads from the GBWT as vg Paths
echo "vg paths --xg $PREFIX.xg --gbwt $PREFIX.gbwt --extract-vg --threads-by _thread_[sample] > [sample]_paths.vg"


## 20 cases from 1kG with SCA allele applied
for INDV in HG00096 HG00097 HG00099 HG00100 HG00101 HG00102 HG00103 HG00105 HG00106 HG00107 HG00108 HG00109 HG00110 HG00111 HG00112 HG00113 HG00114 HG00115 HG00116 HG00117
do
    vg paths --xg $PREFIX.xg --gbwt $PREFIX.gbwt --extract-vg --paths-by _thread_${INDV} > ${INDV}_paths.vg
done
    
## 20 controls from 1kG
for INDV in HG00118 HG00119 HG00120 HG00121 HG00122 HG00123 HG00125 HG00126 HG00127 HG00128 HG00129 HG00130 HG00131 HG00132 HG00133 HG00136 HG00137 HG00138 HG00139 HG00140
do
    vg paths --xg $PREFIX.xg --gbwt $PREFIX.gbwt --extract-vg --paths-by _thread_${INDV} > ${INDV}_paths.vg
done

# now add those paths back to the vg
cat $PREFIX.vg *_paths.vg > $PREFIX.paths.vg
## rm *_paths.vg

# output some nice files
vg view --threads 64 --gfa $PREFIX.paths.vg > $PREFIX.paths.gfa
vg view --threads 64 --json $PREFIX.paths.vg > $PREFIX.paths.json
vg view --threads 64 --dot $PREFIX.paths.vg > $PREFIX.paths.dot
dot -Tpdf $PREFIX.paths.dot > $PREFIX.paths.pdf
