#!/bin/sh
VCF="/erdos/shokin/1kG/ALL.chr11.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz"

REGION=HBB
CHR=11
START=5246696
END=5248301
KEEPLIST="keeplist-500"

vcftools --gzvcf $VCF --keep $KEEPLIST --recode --recode-INFO-all --chr $CHR --from-bp $START --to-bp $END --out $REGION
vcf2tbi $REGION.recode.vcf
