#!/bin/sh

DIR=HBB.20k

vcf-merge -R "0/0"  \
	  $DIR/HG00096.recode.vcf.gz \
	  $DIR/HG00097.recode.vcf.gz \
	  $DIR/HG00099.recode.vcf.gz \
	  $DIR/HG00100.recode.vcf.gz \
	  $DIR/HG00101.recode.vcf.gz \
	  $DIR/HG00102.recode.vcf.gz \
	  $DIR/HG00103.recode.vcf.gz \
	  $DIR/HG00105.recode.vcf.gz \
	  $DIR/HG00106.recode.vcf.gz \
	  $DIR/HG00107.recode.vcf.gz \
	  $DIR/HG00108.recode.vcf.gz \
	  $DIR/HG00109.recode.vcf.gz \
	  $DIR/HG00110.recode.vcf.gz \
	  $DIR/HG00111.recode.vcf.gz \
	  $DIR/HG00112.recode.vcf.gz \
	  $DIR/HG00113.recode.vcf.gz \
	  $DIR/HG00114.recode.vcf.gz \
	  $DIR/HG00115.recode.vcf.gz \
	  $DIR/HG00116.recode.vcf.gz \
	  $DIR/HG00117.recode.vcf.gz \
	  $DIR/HG00118.recode.vcf.gz \
	  $DIR/HG00119.recode.vcf.gz \
	  $DIR/HG00120.recode.vcf.gz \
	  $DIR/HG00121.recode.vcf.gz \
	  $DIR/HG00122.recode.vcf.gz \
	  $DIR/HG00123.recode.vcf.gz \
	  $DIR/HG00125.recode.vcf.gz \
	  $DIR/HG00126.recode.vcf.gz \
	  $DIR/HG00127.recode.vcf.gz \
	  $DIR/HG00128.recode.vcf.gz \
	  $DIR/HG00129.recode.vcf.gz \
	  $DIR/HG00130.recode.vcf.gz \
	  $DIR/HG00131.recode.vcf.gz \
	  $DIR/HG00132.recode.vcf.gz \
	  $DIR/HG00133.recode.vcf.gz \
	  $DIR/HG00136.recode.vcf.gz \
	  $DIR/HG00137.recode.vcf.gz \
	  $DIR/HG00138.recode.vcf.gz \
	  $DIR/HG00139.recode.vcf.gz \
	  $DIR/HG00140.recode.vcf.gz \
	  > $DIR.vcf

vcf2tbi $DIR.vcf
