scripts/search-abstracts-text 10000 "Aeschynomene evenia" > data/Aeschynomene.evenia.txt
scripts/search-abstracts-text 10000 "Apios americana" > data/Apios.americana.txt
scripts/search-abstracts-text 10000 "Arachis cardenasii" > data/Arachis.cardenasii.txt
scripts/search-abstracts-text 10000 "Arachis duranensis" > data/Arachis.duranensis.txt
scripts/search-abstracts-text 10000 "Arachis hypogaea" > data/Arachis.hypogaea.txt
scripts/search-abstracts-text 10000 "Arachis ipaensis" > data/Arachis.ipaensis.txt
scripts/search-abstracts-text 10000 "Arachis stenosperma" > data/Arachis.stenosperma.txt
scripts/search-abstracts-text 10000 "Bauhinia blakeana" > data/Bauhinia.blakeana.txt
scripts/search-abstracts-text 10000 "Bauhinia purpurea" > data/Bauhinia.purpurea.txt
scripts/search-abstracts-text 10000 "Bauhinia tomentosa" > data/Bauhinia.tomentosa.txt
scripts/search-abstracts-text 10000 "Bauhinia variegata" > data/Bauhinia.variegata.txt
scripts/search-abstracts-text 10000 "Cajanus cajan" > data/Cajanus.cajan.txt
scripts/search-abstracts-text 10000 "Cercis canadensis" > data/Cercis.canadensis.txt
scripts/search-abstracts-text 10000 "Cercis gigantea" > data/Cercis.gigantea.txt
scripts/search-abstracts-text 10000 "Chamaecrista fasciculata" > data/Chamaecrista.fasciculata.txt
scripts/search-abstracts-text 10000 "Cicer arietinum" > data/Cicer.arietinum.txt
scripts/search-abstracts-text 10000 "Cicer echinospermum" > data/Cicer.echinospermum.txt
scripts/search-abstracts-text 10000 "Cicer reticulatum" > data/Cicer.reticulatum.txt
scripts/search-abstracts-text 10000 "Faidherbia albida" > data/Faidherbia.albida.txt
scripts/search-abstracts-text 10000 "Glycine cyrtoloba" > data/Glycine.cyrtoloba.txt
scripts/search-abstracts-text 10000 "Glycine tomentella" > data/Glycine.tomentella.txt
scripts/search-abstracts-text 10000 "Glycine dolichocarpa" > data/Glycine.dolichocarpa.txt
scripts/search-abstracts-text 10000 "Glycine falcata" > data/Glycine.falcata.txt
scripts/search-abstracts-text 10000 "Glycine max" > data/Glycine.max.txt
scripts/search-abstracts-text 10000 "Glycine soja" > data/Glycine.soja.txt
scripts/search-abstracts-text 10000 "Glycine stenophita" > data/Glycine.stenophita.txt
scripts/search-abstracts-text 10000 "Glycine syndetika" > data/Glycine.syndetika.txt
scripts/search-abstracts-text 10000 "Lens culinaris" > data/Lens.culinaris.txt
scripts/search-abstracts-text 10000 "Lens ervoides" > data/Lens.ervoides.txt
scripts/search-abstracts-text 10000 "Lotus japonicus" > data/Lotus.japonicus.txt
scripts/search-abstracts-text 10000 "Lupinus albus" > data/Lupinus.albus.txt
scripts/search-abstracts-text 10000 "Lupinus angustifolius" > data/Lupinus.angustifolius.txt
scripts/search-abstracts-text 10000 "Medicago polymorpha" > data/Medicago.polymorpha.txt
scripts/search-abstracts-text 10000 "Medicago ruthenica" > data/Medicago.ruthenica.txt
scripts/search-abstracts-text 10000 "Medicago sativa" > data/Medicago.sativa.txt
scripts/search-abstracts-text 10000 "Medicago truncatula" > data/Medicago.truncatula.txt
scripts/search-abstracts-text 10000 "Phaseolus acutifolius" > data/Phaseolus.acutifolius.txt
scripts/search-abstracts-text 10000 "Phaseolus lunatus" > data/Phaseolus.lunatus.txt
scripts/search-abstracts-text 10000 "Phaseolus vulgaris" > data/Phaseolus.vulgaris.txt
scripts/search-abstracts-text 10000 "Pisum sativum" > data/Pisum.sativum.txt
scripts/search-abstracts-text 10000 "Trifolium pratense" > data/Trifolium.pratense.txt
scripts/search-abstracts-text 10000 "Trifolium subterraneum" > data/Trifolium.subterraneum.txt
scripts/search-abstracts-text 10000 "Vigna angularis" > data/Vigna.angularis.txt
scripts/search-abstracts-text 10000 "Vigna radiata" > data/Vigna.radiata.txt
scripts/search-abstracts-text 10000 "Vigna unguiculata" > data/Vigna.unguiculata.txt
scripts/search-abstracts-text 10000 "Zenia insignis" > data/Zenia.insignis.txt
