#!/bin/sh

prefix=$1

## remove files from a previous run
rm -f $prefix.1.*.txt
rm -f $prefix.2.*.txt
rm -f $prefix.3.*.txt
rm -f $prefix.4.*.txt
rm -f $prefix.5.*.txt
rm -f $prefix.10.*.txt
rm -f $prefix.20.*.txt
rm -f $prefix.30.*.txt
rm -f $prefix.40.*.txt
rm -f $prefix.50.*.txt
rm -f $prefix.60.*.txt
rm -f $prefix.70.*.txt
rm -f $prefix.80.*.txt

## post-process with a range of minsup, minsize, minlen
java -server -cp "build/install/fr/lib/*" org.ncgr.pangenomics.fr.FRFinder --debug --inputprefix $prefix --minsup 1 --minsize 1 --minlen 1
java -server -cp "build/install/fr/lib/*" org.ncgr.pangenomics.fr.FRFinder --debug --inputprefix $prefix --minsup 1 --minsize 1 --minlen 2
java -server -cp "build/install/fr/lib/*" org.ncgr.pangenomics.fr.FRFinder --debug --inputprefix $prefix --minsup 1 --minsize 1 --minlen 5
java -server -cp "build/install/fr/lib/*" org.ncgr.pangenomics.fr.FRFinder --debug --inputprefix $prefix --minsup 1 --minsize 1 --minlen 10
java -server -cp "build/install/fr/lib/*" org.ncgr.pangenomics.fr.FRFinder --debug --inputprefix $prefix --minsup 1 --minsize 1 --minlen 20

## run SVM on the above
./run-svm $prefix 1 1 1
./run-svm $prefix 1 1 2
./run-svm $prefix 1 1 5
./run-svm $prefix 1 1 10
./run-svm $prefix 1 1 20
