#!/bin/sh

MEM=30

C=$1
gamma=$2

DOT="HDStudy+1kG.HTT.$MEM"
FASTA="HDStudy+1kG.HTT"

FRDIR="FR-$DOT.dot-$FASTA.fasta"

TRAIN="$FRDIR/$DOT.train"
MODEL="$TRAIN.model"

TEST="$FRDIR/$DOT.test"
TESTSCALE="$TEST.scale"
PREDICT="$TEST.predict"

# blow away the prediction from a previous run
rm -f $PREDICT

# now run the predictor on the scaled test data with this model
java -cp build/install/fr/lib/fr.jar:build/install/fr/lib/commons-cli-1.4.jar org.ncgr.svm.SvmPredictor $TESTSCALE $MODEL $PREDICT

# compare to what it should be
echo "TESTS:"
echo "1	1	1	1	1	1	1	-1	-1	-1	-1	-1	-1	-1"
echo "PREDICTIONS:"
cat $PREDICT
echo ""
