#!/bin/sh

MEM=30

C=8.0
gamma=0.0078125

DOT="HDStudy+1kG.HTT.$MEM"
FASTA="HDStudy+1kG.HTT"

FRDIR="FR-$DOT.dot-$FASTA.fasta"

BOTH="$FRDIR/$DOT.both"

BOTHSCALE="$BOTH.scale"

# cross validate on full dataset
ARGS="-v 10 -c $C -g $gamma $BOTHSCALE"
echo "SvmCrossValidator $ARGS"
java -cp build/install/fr/lib/fr.jar:build/install/fr/lib/commons-cli-1.4.jar org.ncgr.svm.SvmCrossValidator $ARGS
