#!/bin/sh

prefix=$1
minsup=$2
minsize=$3
minlen=$4

FRFILE="$prefix.frs.txt"
SVMROOT="$prefix-$minsup.$minsize.$minlen"
SVMFRFILE="$SVMROOT.frs.txt"

if [ -s $FRFILE ]
then

    ## post-process
    java -server -cp "build/install/fr/lib/*" org.ncgr.pangenomics.fr.FRFinder \
	    --debug --prunedgraph --inputprefix $prefix --minsup $minsup --minsize $minsize --minlen $minlen
    
    ## run SVM
    if [ -s $SVMFRFILE ]
    then
        for i in 1 2 3
        do
	    ./run-svm $SVMROOT > "$SVMROOT-$i.crossvalidation.txt"
        done
    fi
    
    ## clean up
    rm -f "$SVMROOT.frs.txt"
    rm -f "$SVMROOT.arff"
    rm -f "$SVMROOT.svm.txt"
    rm -f "$SVMROOT.svm.range.txt"
    rm -f "$SVMROOT.svm.scale.txt"
    rm -f "$SVMROOT.svm.grid.txt"

fi


