#!/bin/sh
# usage: FRViewer
#  -d,--decorateedges         decorate edges according to the number of
#                             paths [false]
#  -h,--highlightpath <arg>   path to highlight
#  -p,--prefix <arg>          prefix of FR files, e.g. HLAB.601-1.0-0
 
prefix=$1

java -cp "build/install/fr/lib/*" -XX:+UseStringDeduplication -XX:+UseG1GC org.ncgr.pangenomics.fr.FRViewer -p $prefix $2 $3 $4 $5 $6
