#!/bin/sh

MEM=30

#C=8.0
#gamma=0.0078125

C=2048.0
gamma=4.8828125E-4

DOT="HDStudy+1kG.HTT.$MEM"
FASTA="HDStudy+1kG.HTT"

FRDIR="FR-$DOT.dot-$FASTA.fasta"

TRAIN="$FRDIR/$DOT.train"

TRAINSCALE="$TRAIN.scale"

# train on the scaled training set for cross validation
echo "SvmCrossValidator -q -v 5 -c $C -g $gamma $TRAINSCALE"
java -cp build/install/fr/lib/fr.jar:build/install/fr/lib/commons-cli-1.4.jar org.ncgr.svm.SvmCrossValidator -q -v 5 -c $C -g $gamma $TRAINSCALE
