#!/bin/sh
# algorithm
#  -a,--alpha <arg>          alpha=penetrance, fraction of a supporting path's sequence that supports the FR (required)
#  -k,--kappa <arg>          kappa=maximum insertion length that any supporting path may have (required)
#  -cc,--casectrl            emphasize FRs that have large case vs. control support (false)
# input
#  -d,--dot <arg>            splitMEM DOT file (requires FASTA file)
#  -f,--fasta <arg>          FASTA file (requires DOT file)
#  -g,--genotype <arg>       which genotype to include (0,1) from the input file; -1 to include all (-1)
#  -j,--json <arg>           vg JSON file
#  -gfa,--gfa <arg>          GFA file
#  -p,--pathlabels <arg>     tab-delimited file with pathname<tab>label
# post-processing input
#  -i,--inputprefix <arg>    input file prefix for further processing (=outputprefix from previous run)
#  -m,--minsup <arg>         minsup=minimum number of supporting paths for a region to be considered interesting (1)
#  -s,--minsize <arg>        minsize=minimum number of nodes that a FR must contain to be considered interesting (1)
#  -l,--minlen <arg>         minlen=minimum allowed average length (bp) of an FR's subpaths (1)
# output
#  -o,--outputprefix <arg>   output file prefix (stdout)
# other
#  -go,--graphonly           just read the graph and output, do not find FRs; for debuggery (false)
#  -v,--verbose              verbose output (false)
#  -do,--debug               debug output (false)

## initial run
java -server -cp "build/install/fr/lib/*" org.ncgr.pangenomics.fr.FRFinder --gfa SCA/HBB.paths.gfa  \
     --pathlabels SCA/labels.txt --outputprefix sca \
     --alpha 1.0 --kappa 0 --debug --casectrl

