#!/bin/sh

MEM=30

C=8.0
gamma=0.0078125

DOT="HDStudy+1kG.HTT.$MEM"
FASTA="HDStudy+1kG.HTT"

FRDIR="FR-$DOT.dot-$FASTA.fasta"

TRAIN="$FRDIR/$DOT.train"

MODEL="$TRAIN.model"
TRAINSCALE="$TRAIN.scale"

# blow away the model from a previous run
rm -f $MODEL

# train on the scaled training set with the above parameters to get the model
echo "java -cp build/install/fr/lib/fr.jar:build/install/fr/lib/commons-cli-1.4.jar org.ncgr.svm.SvmTrainer -c $C -g $gamma $TRAINSCALE $MODEL"
java -cp build/install/fr/lib/fr.jar:build/install/fr/lib/commons-cli-1.4.jar org.ncgr.svm.SvmTrainer -c $C -g $gamma $TRAINSCALE $MODEL
