#!/bin/sh
# -1 --onebased flag to number FR IDs from 1 rather than 0
# -a --alpha    the fraction of a supporting strain's sequence that actually supports the FR; alternatively, `1-alpha` is the fraction of inserted sequence
# -k --kappa    the maximum insertion length (measured in bp) that any supporting path may have
# -m --minsup   [1] minimum number of genome paths in order for a region to be considered frequent
# -z --minsize  [1] minimum number of de Bruijn nodes that an FR must contain to be considered frequent
# -r --rc       flag to indicate whether the sequence (e.g. FASTA file) had its reverse complement appended

java -cp build/install/fr/lib/fr.jar:build/install/fr/lib/commons-cli-1.4.jar:build/install/fr/lib/protobuf-java-3.6.1.jar:build/install/fr/lib/protobuf-java-util-3.6.1.jar:build/install/fr/lib/gson-2.7.jar \
     org.ncgr.pangenomics.fr.FRFinder -j HDStudy/HDStudy.HTT.paths.json  --alpha 0.1 --kappa 54 --minsup 5 --maxsup 36 --minsize 1 --minlen 100 -p HDStudy/HDStudy.labels.txt -v
