#!/bin/sh
## analysis parameters
# -a,--alpha <arg>        alpha=penetrance, fraction of a supporting path's sequence that supports the FR (required)
# -k,--kappa <arg>        kappa=maximum insertion length that any supporting path may have (required)
# -l,--minlen <arg>       minlen=minimum allowed average length (bp) of an FR's subpaths (1)
# -m,--minsup <arg>       minsup=minimum number of supporting paths for a region to be considered interesting (1)
# -n,--maxsup <arg>       maxsup=maximum number of supporting paths for a region to be considered interesting (2147483647)
# -s,--minsize <arg>      minsize=minimum number of nodes that a FR must contain to be considered interesting (1)
## I/O
# -d,--dot <arg>          splitMEM DOT file (requires FASTA file)
# -f,--fasta <arg>        FASTA file (requires DOT file)
# -j,--json <arg>         vg JSON file
# -g,--genotype <arg>     which genotype to include (0,1) from the input file; -1 to include all (-1)
# -p,--pathlabels <arg>   tab-delimited file with pathname<tab>label
# -o,--outputfile <arg>   output file (stdout)
# -r,--userc              indicates if the sequence (e.g. FASTA) had its reverse complement appended (false)
## other
# -pa,--parallel          run FR-building loop in parallel (false)
# -rc,--removechildren    remove child FRs that have equal or lower support (false)
# -v,--verbose            verbose output (false)
# -go,--graphonly         just read the graph and output, do not find FRs; for debuggery (false)
# -nr,--nrounds <arg>     number of FR-building rounds to run (2)
# -do,--debug             debug output (false)

java -server -cp lib/fr.jar:lib/commons-cli-1.4.jar:lib/protobuf-java-3.6.1.jar:lib/protobuf-java-util-3.6.1.jar:lib/gson-2.7.jar org.ncgr.pangenomics.fr.FRFinder \
	--json HDStudy/HTT.paths.json --pathlabels HDStudy/labels.txt --genotype 1 \
	--alpha 0.1 --kappa 1 --minsup 1 --maxsup 99 --minsize 1 --minlen 100 \
	--nrounds 2 --parallel --debug  \
	--outputfile hdstudy.all.out
