#!/bin/sh
# usage: PangenomicGraph
#  -gfa,--gfa                load from a vg GFA file
#  -graph,--graph <arg>      name of graph
#  -gt,--genotype <arg>      which genotype to include (0,1) from the GFA
#                            file; -1 to include both (-1)
#  -o,--outputprefix <arg>   output file prefix (stdout)
#  -p,--pathlabels <arg>     tab-delimited file containing one
#                            pathname<tab>label per line
#  -se,--skipedges           skip adding edges to graph (false)
#  -snp,--skipnodepaths      skip building list of paths per node (false)
#  -ss,--skipsequences       skip building sequences of paths (false)
#  -txt,--txt                load from previously dumped TXT files
#  -v,--verbose              verbose output (false)

dir=$1
graph=$2

java -server -cp "build/install/fr/lib/*" org.ncgr.jgraph.PangenomicGraph --verbose \
     --gfa --graph $dir/$graph --pathlabels $dir/labels.txt --outputprefix $graph --skipedges --skipsequences --skipnodepaths

#java -server -cp "build/install/fr/lib/*" org.ncgr.jgraph.PangenomicGraph --verbose \
#     --txt --graph $graph --outputprefix $graph --skipedges --skipsequences --skipnodepaths
