#!/bin/sh
# usage: FRFinder
#  -ae,--alphaend <arg>          ending value of alpha for a scan (can equal
#                                alphastart)
#  -as,--alphastart <arg>        starting value of alpha for a scan (can
#                                equal alphaend)
#  -do,--debug                   debug output [false]
#  -g,--genotype <arg>           which genotype to include (0,1) from the
#                                input file; -1 to include all [-1]
#  -gfa,--gfa <arg>              GFA file
#  -i,--inputprefix <arg>        input file prefix for post-processing
#  -ke,--kappaend <arg>          ending value of kappa for a scan (can equal
#                                kappastart)
#  -ks,--kappastart <arg>        starting value of kappa for a scan (can
#                                equal kappaend)
#  -l,--minlen <arg>             minimum allowed average length (bp) of an
#                                FR's subpaths [1.0]
#  -m,--minsup <arg>             minimum number of supporting paths for a
#                                region to be considered interesting [1]
#  -mp,--minpriority <arg>       minimum priority for saving an FR [0]
#  -mr,--maxround <arg>          maximum FR-finding round to run
#                                [0=unlimited]
#  -p,--pathlabels <arg>         tab-delimited file with pathname<tab>label
#  -pr,--prunedgraph             prune graph -- remove all common nodes
#                                [false]
#  -pri,--priorityoption <arg>   option for priority weighting of FRs:
#                                0=total support, 1=case support-control
#                                support, 2=|case support-control support|,
#                                3=Fisher's exact test double-sided p value,
#                                4=control support (descending)
#  -r,--resume                   resume from a previous run [false]
#  -s,--minsize <arg>            minimum number of nodes that a FR must
#                                contain to be considered interesting [1]
#  -snp,--skipnodepaths          skip building list of paths per node
#                                [false]
#  -ssf,--skipsavefiles          skip saving files after each FR is found,
#                                to save time [false]
#  -v,--verbose                  verbose output [false]


## perfect path matching to FR is alpha=1, kappa=0

dir=$1
prefix=$2
alpha=$3
kappa=$4
priorityoption=$5

## use $6 and $7 for extra stuff like --resume --debug

echo "# $dir $prefix alpha=$alphastart-$alphaend kappa=$kappastart-$kappaend priority=$priority"

java -server -Xmx160g -XX:+UseParallelGC -Xms2g -XX:SoftRefLRUPolicyMSPerMB=1 -XX:MaxHeapFreeRatio=99 -cp "build/install/fr/lib/*" org.ncgr.pangenomics.fr.FRFinder \
     --priorityoption=$priorityoption --skipnodepaths $6 $7 \
     --pathlabels=$dir/labels.txt --gfa=$dir/$prefix.paths.gfa \
     --alphastart=$alpha --alphaend=$alpha --kappastart=$kappa --kappaend=$kappa
