#!/bin/sh
# usage: SvmScaler
# -l <arg>   x scaling lower limit [-1]
# -r <arg>   filename to read scaling parameters from
# -s <arg>   filename to save scaling parameters to
# -u <arg>   x scaling upper limit [+1]
# -y <arg>   y scaling limits yLower,yUpper [no y scaling]

FULL="hdstudy.svm.txt"
RANGE="hdstudy.svm.range.txt"
FULLSCALE="hdstudy.svm.scale.txt"

TRAIN="hdstudy.train.txt"
TEST="hdstudy.test.txt"
TRAINSCALE="hdstudy.train.scale.txt"
TESTSCALE="hdstudy.test.scale.txt"

GRIDOUT="hdstudy.grid.txt"
MODEL="hdstudy.model.txt"
PREDICT="hdstudy.predict.txt"

# scale the full data
echo "-------------------------"
echo "SvmScaler -s $RANGE $FULL > $FULLSCALE"
java -cp "build/install/fr/lib/*" org.ncgr.svm.SvmScaler -s $RANGE $FULL > $FULLSCALE

# # apply scale factors to training and testing subsets
# echo "-------------------------"
# echo "SvmScaler -r $RANGE $TRAIN > $TRAINSCALE"
# java -cp "build/install/fr/lib/*" org.ncgr.svm.SvmScaler -r $RANGE $TRAIN > $TRAINSCALE
# echo "-------------------------"
# echo "SvmScaler -r $RANGE $TEST > $TESTSCALE"
# java -cp "build/install/fr/lib/*" org.ncgr.svm.SvmScaler -r $RANGE $TEST > $TESTSCALE

# run GridSearcher on the full scaled data
ARGS="-log2c -5,15,2 -log2g 3,-15,-2 -k 10"
echo "-------------------------"
echo "GridSearcher $ARGS $FULLSCALE"
java -cp "build/install/fr/lib/*" org.ncgr.svm.GridSearcher $ARGS  $FULLSCALE > $GRIDOUT
C=`tail -1 $GRIDOUT | awk '{ print $1; }'`
gamma=`tail -1 $GRIDOUT | awk '{ print $2; }'`
perc=`tail -1 $GRIDOUT | awk '{ print $3; }'`
echo "C=$C"
echo "gamma=$gamma"
echo "perc=$perc"

# # train on the scaled training set with the above parameters to get the model
# echo "-------------------------"
# echo "SvmTrainer -c $C -g $gamma $TRAINSCALE $MODEL"
# java -cp "build/install/fr/lib/*" org.ncgr.svm.SvmTrainer -c $C -g $gamma $TRAINSCALE $MODEL

# # now run the predictor on the scaled test data with this model
# echo "-------------------------"
# echo "SvmPredictor $TESTSCALE $MODEL $PREDICT"
# java -cp "build/install/fr/lib/*" org.ncgr.svm.SvmPredictor $TESTSCALE $MODEL $PREDICT

# cross validate on full dataset
ARGS="-c $C -g $gamma -k 10"
echo "-------------------------"
echo "SvmCrossValidator $ARGS $FULLSCALE"
java -cp "build/install/fr/lib/*" org.ncgr.svm.SvmCrossValidator $ARGS $FULLSCALE
