#!/bin/sh
#
# -a --alpha   the fraction of a supporting strain's sequence that actually supports the FR; alternatively, `1-alpha` is the fraction of inserted sequence
# -k --kappa   the maximum insertion length (measured in bp) that any supporting path may have
# -m --minsup  [1] minimum number of genome paths in order for a region to be considered frequent
# -z --minsize [1] minimum number of de Bruijn nodes that an FR must contain to be considered frequent
# -r --rc      flag to indicate whether the sequence (e.g. FASTA file) had its reverse complement appended

DOT=HTT.full+var.141.dot
FASTA=HTT.full+var.fasta
FRDIR="FR-$DOT-$FASTA"

# run FRFinder

build/install/fr/bin/fr FRFinder -d HTT/$DOT -f HTT/$FASTA -a 0.1 -k 2 -m 1 -z 1"

# munge the CSFR file so it can be loaded by libsvm

echo ""
echo "#################### libsvm ####################"

grep HTTtrain $FRDIR/*.csfr.txt > $FRDIR/HTT.0.train
grep HTTvar   $FRDIR/*.csfr.txt > $FRDIR/HTT.0.test

sed s/HTTtrain18/-1/ $FRDIR/HTT.0.train > $FRDIR/HTT.1.train
sed s/HTTtrain40/+1/ $FRDIR/HTT.1.train > $FRDIR/HTT.0.train
sed s/HTTtrain19/-1/ $FRDIR/HTT.0.train > $FRDIR/HTT.1.train
sed s/HTTtrain41/+1/ $FRDIR/HTT.1.train > $FRDIR/HTT.0.train
sed s/HTTtrain20/-1/ $FRDIR/HTT.0.train > $FRDIR/HTT.1.train
sed s/HTTtrain42/+1/ $FRDIR/HTT.1.train > $FRDIR/HTT.0.train
sed s/HTTtrain21/-1/ $FRDIR/HTT.0.train > $FRDIR/HTT.1.train
sed s/HTTtrain43/+1/ $FRDIR/HTT.1.train > $FRDIR/HTT.0.train
sed s/HTTtrain22/-1/ $FRDIR/HTT.0.train > $FRDIR/HTT.1.train
sed s/HTTtrain44/+1/ $FRDIR/HTT.1.train > $FRDIR/HTT.0.train
sed s/HTTtrain23/-1/ $FRDIR/HTT.0.train > $FRDIR/HTT.1.train
sed s/HTTtrain45/+1/ $FRDIR/HTT.1.train > $FRDIR/HTT.0.train
sed s/HTTtrain24/-1/ $FRDIR/HTT.0.train > $FRDIR/HTT.1.train
sed s/HTTtrain46/+1/ $FRDIR/HTT.1.train > $FRDIR/HTT.0.train
sed s/HTTtrain25/-1/ $FRDIR/HTT.0.train > $FRDIR/HTT.1.train
sed s/HTTtrain47/+1/ $FRDIR/HTT.1.train > $FRDIR/HTT.0.train

sed s/HTTvar1/-1/ $FRDIR/HTT.0.test > $FRDIR/HTT.1.test
sed s/HTTvar2/-1/ $FRDIR/HTT.1.test > $FRDIR/HTT.0.test
sed s/HTTvar3/-1/ $FRDIR/HTT.0.test > $FRDIR/HTT.1.test
sed s/HTTvar4/-1/ $FRDIR/HTT.1.test > $FRDIR/HTT.0.test
sed s/HTTvar5/-1/ $FRDIR/HTT.0.test > $FRDIR/HTT.1.test
sed s/HTTvar6/-1/ $FRDIR/HTT.1.test > $FRDIR/HTT.0.test
sed s/HTTvar7/-1/ $FRDIR/HTT.0.test > $FRDIR/HTT.1.test
sed s/HTTvar8/+1/ $FRDIR/HTT.1.test > $FRDIR/HTT.0.test

sed s/,/\ /g $FRDIR/HTT.0.train > $FRDIR/HTT.1.train
sed s/,/\ /g $FRDIR/HTT.0.test > $FRDIR/HTT.1.test

rm $FRDIR/HTT.0.train
rm $FRDIR/HTT.0.test
mv $FRDIR/HTT.1.train $FRDIR/HTT.train
mv $FRDIR/HTT.1.test  $FRDIR/HTT.test

./easy.py $FRDIR/HTT.train $FRDIR/HTT.test
