#!/bin/sh

VCFFILE=$1

#java -server -Xms1g -Xmx600g -XX:+UseG1GC -XX:+UseStringDeduplication -cp "build/install/fr/lib/*" org.ncgr.pangenomics.GenotypeGraph -vf $VCFFILE

java -cp "build/install/fr/lib/*" org.ncgr.pangenomics.GenotypeGraph -vf $VCFFILE

