#!/bin/sh

MEM=30
FASTA="HDStudy+1kG.HTT"

DOT="HDStudy+1kG.HTT.$MEM"
FRDIR="FR-$DOT.dot-$FASTA.fasta"

RANGE="$DOT.range"
TRAIN="$FRDIR/$DOT.train"
SCALE="$DOT.scale"

java -cp build/install/fr/lib/fr.jar SvmScale -s $RANGE $TRAIN > $SCALE
