#!/bin/sh
# -1 --onebased flag to number FR IDs from 1 rather than 0
# -a --alpha    the fraction of a supporting strain's sequence that actually supports the FR; alternatively, `1-alpha` is the fraction of inserted sequence
# -k --kappa    the maximum insertion length (measured in bp) that any supporting path may have
# -m --minsup   [1] minimum number of genome paths in order for a region to be considered frequent
# -z --minsize  [1] minimum number of de Bruijn nodes that an FR must contain to be considered frequent
# -r --rc       flag to indicate whether the sequence (e.g. FASTA file) had its reverse complement appended

rm -rf FR-ecoli.pan3.dot-ecoli.pan3.fa

java -cp build/install/fr/lib/fr.jar:build/install/fr/lib/commons-cli-1.4.jar \
     org.ncgr.pangenomics.fr.FRFinder -d sample/ecoli.pan3.dot -f sample/ecoli.pan3.fa -a 0.5 -k 3

echo ""
echo "The following FIVE file comparisons should all report as identical:"
echo ""
diff -s FR-ecoli.pan3.dot-ecoli.pan3.fa/FR-a0.5-kp3-sup1-sz1.bed         gold-ecoli.pan3.dot-ecoli.pan3.fa/FR-a0.5-kp3-sup1-sz1.bed
diff -s FR-ecoli.pan3.dot-ecoli.pan3.fa/FR-a0.5-kp3-sup1-sz1.csfr.txt    gold-ecoli.pan3.dot-ecoli.pan3.fa/FR-a0.5-kp3-sup1-sz1.csfr.txt
diff -s FR-ecoli.pan3.dot-ecoli.pan3.fa/FR-a0.5-kp3-sup1-sz1.dist.txt    gold-ecoli.pan3.dot-ecoli.pan3.fa/FR-a0.5-kp3-sup1-sz1.dist.txt
diff -s FR-ecoli.pan3.dot-ecoli.pan3.fa/FR-a0.5-kp3-sup1-sz1.frpaths.txt gold-ecoli.pan3.dot-ecoli.pan3.fa/FR-a0.5-kp3-sup1-sz1.frpaths.txt
diff -s FR-ecoli.pan3.dot-ecoli.pan3.fa/FR-a0.5-kp3-sup1-sz1.frs.txt     gold-ecoli.pan3.dot-ecoli.pan3.fa/FR-a0.5-kp3-sup1-sz1.frs.txt
