#!/bin/sh
#
# -log2c range/step of C [-5,15,2]
# -log2g range/step of gamma [3,-15,-2]
# -v n-fold cross validation [5]

MEM=30

FASTA="HDStudy+1kG.HTT"
DOT="HDStudy+1kG.HTT.$MEM"

FRDIR="FR-$DOT.dot-$FASTA.fasta"

# SVM files
BOTH="$FRDIR/$DOT.both"

BOTHSCALE="$BOTH.scale"

ARGS="-log2c -5,15,2 -log2g 3,-15,-2 -n 5 $BOTHSCALE"

# run Grid
echo "GridSearcher $ARGS"
java -cp build/install/fr/lib/fr.jar:build/install/fr/lib/commons-cli-1.4.jar org.ncgr.svm.GridSearcher $ARGS
