#!/bin/sh

prefix=$1
minsup=$2
minsize=$3
minlen=$4

FULL="$prefix.$minsup.$minsize.$minlen.svm.txt"
FULLSCALE="$prefix.$minsup.$minsize.$minlen.svm.scale.txt"
RANGE="$prefix.$minsup.$minsize.$minlen.svm.range.txt"
GRIDOUT="$prefix.$minsup.$minsize.$minlen.svm.grid.txt"

echo "-------------------------"
echo "$FULL"

## scale the full data (if exists)
if [ -s $FULL ]
then
    java -cp "build/install/fr/lib/*" org.ncgr.svm.SvmScaler -s $RANGE $FULL > $FULLSCALE
else
    echo "NO FILE."
fi

## run GridSearcher on the full scaled data (if exists) to find optimum SVM parameters
if [ -s $FULLSCALE ]
then
    ARGS="-log2c -5,15,2 -log2g 3,-15,-2 -k 10"
    java -cp "build/install/fr/lib/*" org.ncgr.svm.GridSearcher $ARGS  $FULLSCALE > $GRIDOUT
fi

## cross validate on full dataset with the above parameters
if [ -s $GRIDOUT ]
then
    C=`tail -1 $GRIDOUT | awk '{ print $1; }'`
    gamma=`tail -1 $GRIDOUT | awk '{ print $2; }'`
    perc=`tail -1 $GRIDOUT | awk '{ print $3; }'`

    ARGS="-c $C -g $gamma -k 5"
    java -cp "build/install/fr/lib/*" org.ncgr.svm.SvmCrossValidator $ARGS $FULLSCALE
fi

## clean up
rm -f $RANGE
rm -f $FULLSCALE
rm -f $GRIDOUT
