#!/bin/sh

prefix=DGCR8.1k

./run-schiz $prefix 0.1 1
./run-schiz $prefix 0.1 3
./run-schiz $prefix 0.1 6
./run-schiz $prefix 0.1 9
./run-schiz $prefix 0.1 12
./run-schiz $prefix 0.1 15
./run-schiz $prefix 0.1 18
./run-schiz $prefix 0.1 21


