#!/bin/sh

## run only a single given alpha,kappa value
graph=$1
alpha=$2
kappa=$3

prefix="$graph-$alpha-$kappa"
for minsup in 1 2 4 10 20 50 100
do
    for minsize in 1 2 4 10 20 50 100
    do
        for minlen in 1 2 4 10 20 50 100 500
        do
            ./run-post $prefix $minsup $minsize $minlen
        done
    done
done
