#!/bin/bash

graph=$1
alpha=$2

## special run
kappa=Inf

## no scan
minsup=1
minsize=1

INPUTPREFIX="$graph-$alpha-$kappa-combined"
FRFILE="$INPUTPREFIX.frs.txt"

## post-process with new minSup and minSize
java -server -cp "build/install/fr/lib/*" org.ncgr.pangenomics.genotype.fr.FRUtils -p -i $INPUTPREFIX --minsup=$minsup --minsize=$minsize
