#!/bin/sh
## usage: FrequentedRegion
##  -a,--alpha <arg>              starting value of alpha for a scan (can
##                                equal alphaend)
##  -gfa,--gfa                    load from [graph].paths.gfa
##  -graph,--graph <arg>          graph name
##  -k,--kappa <arg>              starting value of kappa for a scan (can
##                                equal kappaend)
##  -n,--nodes <arg>              set of nodes to calculate FR e.g.
##                                [1,2,3,4,5]
##  -p,--pathlabels <arg>         tab-delimited file with pathname<tab>label
##  -pri,--priorityoption <arg>   option for priority weighting of FRs:
##                                0=total support, 1:label=label
##                                support-other support [case], 2=|case
##                                support-control support|, 3:label=odds
##                                ratio in label's favor [case], 4=Fisher's
##                                exact test double-sided p value
##  -txt,--txt                    load from [graph].nodes.txt and
##                                [graph].paths.txt

graph=$1
alpha=$2
kappa=$3
priorityoption=$4
nodes=$5

java -cp "build/install/fr/lib/*" org.ncgr.pangenomics.genotype.fr.FrequentedRegion \
     --txt --graph=$graph --alpha=$alpha --kappa=$kappa --priorityoption=$priorityoption --nodes=$nodes
