#!/bin/sh
# usage: GridSearcher
#  -k <arg>       k-fold for cross validation [10]
#  -log10C <arg>   set range/step of log10(C) [-5.0,15.0,1.0]
#  -log10gamma <arg>   set range/step of log10(gamma) [-15.0,0.0,1.0]
#  -v             toggle verbose output

INPUTPREFIX=$1

LOG10C=$2
LOG10GAMMA=$3
K=$4

FULLSCALE="$INPUTPREFIX.svm.scale.txt"

## run a single value of C and gamma and k
ARGS="-log10C $LOG10C -log10gamma $LOG10GAMMA -k $K"

java -cp "build/install/fr/lib/*" org.ncgr.svm.GridSearcher -v $ARGS $FULLSCALE
