#!/bin/sh
# usage: PangenomicGraph
#  -g,--graph <arg>          name of graph
#  -gfa,--gfa                load from a vg GFA file
#  -gt,--genotype <arg>      which genotype to include (0,1) from the GFA
#                            file; -1 to include both (-1)
#  -l,--labelfile <arg>      tab-delimited file containing one
#                            sample<tab>label per line
#  -mcn,--mergecommonnodes   merge common adjacent nodes (false)
#  -se,--skipedges           skip adding edges to graph (false)
#  -snp,--skipnodepaths      skip building list of paths per node (false)
#  -ss,--skipsequences       skip building sequences of paths (false)
#  -txt,--txt                load from previously dumped TXT files
#  -v,--verbose              verbose output (false)

GRAPH=$1
LABELSFILE=$2
FILECMD=$3

java -cp "build/install/fr/lib/*" org.ncgr.pangenomics.allele.PangenomicGraph -v -g $GRAPH -l $LABELSFILE $FILECMD 
