#!/bin/sh
# usage: GraphViewer
#  -d,--decorateedges         decorate edges according to the number of
#                             paths [false]
#  -g,--graph <arg>           name of graph
#  -h,--highlightpath <arg>   path to highlight

graph=$1

java -cp "build/install/fr/lib/*" org.ncgr.pangenomics.allele.GraphViewer --graph $1
