#!/bin/sh
# usage: FRFinder
#  -ae,--alphaend <arg>          ending value of alpha for a scan (can equal
#                                alphastart)
#  -as,--alphastart <arg>        starting value of alpha for a scan (can
#                                equal alphaend)
#  -do,--debug                   debug output [false]
#  -fn,--forbiddennodes <arg>    require that found FRs NOT contain the
#                                given nodes []
#  -g,--genotype <arg>           which genotype to include (0,1) from the
#                                input file; -1 to include all [-1]
#  -gfa,--gfa                    load from [graph].paths.gfa
#  -graph,--graph <arg>          graph name
#  -i,--inputprefix <arg>        input file prefix for post-processing
#  -ke,--kappaend <arg>          ending value of kappa for a scan (can equal
#                                kappastart; -1=infinity)
#  -keep,--keepoption <arg>      option for keeping FRs in finder loop:
#                                subset[:N]|distance[:N] [keep all]
#  -ks,--kappastart <arg>        starting value of kappa for a scan (can
#                                equal kappaend; -1=infinity)
#  -l,--minlen <arg>             minimum allowed average length (bp) of an
#                                FR's subpaths [1.0]
#  -m,--minsup <arg>             minimum number of supporting paths for a
#                                region to be considered interesting [1]
#  -mp,--minpriority <arg>       minimum priority for saving an FR [1]
#  -mr,--maxround <arg>          maximum FR-finding round to run
#                                [0=unlimited]
#  -p,--pathlabels <arg>         tab-delimited file with pathname<tab>label
#  -pri,--priorityoption <arg>   option for priority weighting of FRs:
#                                0=total support, 1:label=label
#                                support-other support [case], 2=|case
#                                support-control support|, 3:label=odds
#                                ratio in label's favor [case], 4=Fisher's
#                                exact test double-sided p value
#  -r,--resume                   resume from a previous run [false]
#  -rn,--requirednodes <arg>     require that found FRs contain the given
#                                nodes []
#  -s,--minsize <arg>            minimum number of nodes that a FR must
#                                contain to be considered interesting [1]
#  -snp,--skipnodepaths          skip building list of paths per node
#                                [false]
#  -txt,--txt                    load from [graph].nodes.txt and
#                                [graph].paths.txt
#  -v,--verbose                  verbose output [false]
#  -wsf,--writesavefiles         write save files after each FR is found
#                                [false]

## perfect path matching to FR is alpha=1, kappa=0

graph=$1
alpha=$2
kappa=$3
priorityoption=$4

## use $5-$9 for extra parameters

echo "# $graph alpha=$alpha kappa=$kappa priorityOption=$priorityoption"

## TXT input
java -server -Xms1g -Xmx600g -XX:+UseG1GC -XX:+UseStringDeduplication -cp "build/install/fr/lib/*" org.ncgr.pangenomics.allele.fr.FRFinder \
     --verbose --skipnodepaths --keepoption=subset $5 $6 $7 $8 $9 \
     --txt --graph=$graph \
     --alphastart=$alpha --alphaend=$alpha --kappastart=$kappa --kappaend=$kappa --priorityoption=$priorityoption

## GFA input with path labels file
#java -server -Xmx160g -XX:+UseParallelGC -Xms2g -XX:SoftRefLRUPolicyMSPerMB=1 -XX:MaxHeapFreeRatio=99 -cp "build/install/fr/lib/*" org.ncgr.pangenomics.allele.fr.FRFinder \
#     --priorityoption=$priorityoption --skipnodepaths $5 $6 $7 $8 $9 \
#     --gfa --graph=$dir/$graph --pathlabels=$dir/labels.txt \
#     --alphastart=$alpha --alphaend=$alpha --kappastart=$kappa --kappaend=$kappa
