#!/bin/sh
# usage: FrequentedRegion
#  -a,--alpha <arg>                starting value of alpha for a scan (can
#                                  equal alphaend)
#  -ep,--excludedpathnodes <arg>   exclude paths that include any of the
#                                  given nodes []
#  -gfa,--gfa                      load from [graph].paths.gfa
#  -graph,--graph <arg>            graph name
#  -ip,--includedpathnodes <arg>   include only paths that include at least
#                                  one of the given nodes []
#  -k,--kappa <arg>                starting value of kappa for a scan (can
#                                  equal kappaend)
#  -n,--nodes <arg>                set of nodes to calculate FR e.g.
#                                  [1,2,3,4,5]
#  -p,--pathlabels <arg>           tab-delimited file with
#                                  pathname<tab>label
#  -pri,--priorityoption <arg>     option for priority weighting of FRs:
#                                  0=total support, 1:label=label
#                                  support-other support [case,ctrl,alt],
#                                  2=|case support-control support|,
#                                  3:label=odds ratio in label's favor
#                                  [case,ctrl,alt], 4:label=Fisher's exact
#                                  test double-sided p value
#                                  [null,case,ctrl,alt]
#  -txt,--txt                      load from [graph].nodes.txt and
#                                  [graph].paths.txt

graph=$1
alpha=$2
kappa=$3
priorityoption=$4
nodes=$5

java -cp "build/install/fr/lib/*" org.ncgr.pangenomics.genotype.fr.FrequentedRegion \
     --txt --graph=$graph --alpha=$alpha --kappa=$kappa --priorityoption=$priorityoption --nodes=$nodes $6 $7 $8 $9
