#!/bin/sh
# usage: GridSearcher [options]
#  -k <arg>       k-fold for cross validation [10]
#  -log2c <arg>   set range/step of C [-5,15,2]
#  -log2g <arg>   set range/step of gamma [3,-15,-2]
#  -v             toggle verbose output

INPUTPREFIX=$1

LOG2C=$2
LOG2G=$3
K=10

FULLSCALE="$INPUTPREFIX.svm.scale.txt"

ARGS="-log2c $LOG2C -log2g $LOG2G -k $K"

## run GridSearcher on the full scaled data to find optimum SVM parameters
echo "Running GridSearcher on $FULLSCALE with ARGS=$ARGS"
java -cp "build/install/fr/lib/*" org.ncgr.svm.GridSearcher -v $ARGS $FULLSCALE
