//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.12 at 12:45:05 AM UTC 
//


package org.ncgr.pubag.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded"&gt;
 *         &lt;element ref="{}arr"/&gt;
 *         &lt;element ref="{}bool"/&gt;
 *         &lt;element ref="{}str"/&gt;
 *         &lt;element ref="{}date"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "arrOrBoolOrStr"
})
@XmlRootElement(name = "doc")
public class Doc {

    @XmlElements({
        @XmlElement(name = "arr", type = Arr.class),
        @XmlElement(name = "bool", type = Bool.class),
        @XmlElement(name = "str", type = Str.class),
        @XmlElement(name = "date", type = Date.class)
    })
    protected List<Object> arrOrBoolOrStr;

    /**
     * Gets the value of the arrOrBoolOrStr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the arrOrBoolOrStr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArrOrBoolOrStr().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Arr }
     * {@link Bool }
     * {@link Str }
     * {@link Date }
     * 
     * 
     */
    public List<Object> getArrOrBoolOrStr() {
        if (arrOrBoolOrStr == null) {
            arrOrBoolOrStr = new ArrayList<Object>();
        }
        return this.arrOrBoolOrStr;
    }

}
