//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.12 at 12:45:05 AM UTC 
//


package org.ncgr.pubag.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}bool" minOccurs="0"/&gt;
 *         &lt;element ref="{}int" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}lst" minOccurs="0"/&gt;
 *         &lt;choice&gt;
 *           &lt;element ref="{}arr"/&gt;
 *           &lt;element ref="{}str" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bool",
    "_int",
    "lst",
    "arr",
    "str"
})
@XmlRootElement(name = "lst")
public class Lst {

    protected Bool bool;
    @XmlElement(name = "int")
    protected List<Int> _int;
    protected Lst lst;
    protected Arr arr;
    protected List<Str> str;
    @XmlAttribute(name = "name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String name;

    /**
     * Gets the value of the bool property.
     * 
     * @return
     *     possible object is
     *     {@link Bool }
     *     
     */
    public Bool getBool() {
        return bool;
    }

    /**
     * Sets the value of the bool property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bool }
     *     
     */
    public void setBool(Bool value) {
        this.bool = value;
    }

    /**
     * Gets the value of the int property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the int property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Int }
     * 
     * 
     */
    public List<Int> getInt() {
        if (_int == null) {
            _int = new ArrayList<Int>();
        }
        return this._int;
    }

    /**
     * Gets the value of the lst property.
     * 
     * @return
     *     possible object is
     *     {@link Lst }
     *     
     */
    public Lst getLst() {
        return lst;
    }

    /**
     * Sets the value of the lst property.
     * 
     * @param value
     *     allowed object is
     *     {@link Lst }
     *     
     */
    public void setLst(Lst value) {
        this.lst = value;
    }

    /**
     * Gets the value of the arr property.
     * 
     * @return
     *     possible object is
     *     {@link Arr }
     *     
     */
    public Arr getArr() {
        return arr;
    }

    /**
     * Sets the value of the arr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Arr }
     *     
     */
    public void setArr(Arr value) {
        this.arr = value;
    }

    /**
     * Gets the value of the str property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the str property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStr().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Str }
     * 
     * 
     */
    public List<Str> getStr() {
        if (str == null) {
            str = new ArrayList<Str>();
        }
        return this.str;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
